### ISSUE TITLE
Is it possible to set a ConfigurationSetName header for mail?

### ISSUE THREAD

**Issue by tobybellwood** [blueimp/aws-smtp-relay#1]
We're looking to log email sending in Cloudwatch/Kinesis, but to do so, you need to set a header for a configuration set - is this something that can be (optionally) passed into the mail relay for all traffic?

https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html

**Comment by blueimp** [comment]
Hey @tobybellwood, sorry for my late reply.
I think https://github.com/blueimp/aws-smtp-relay/pull/2 is a good candidate for getting this feature included.
