### ISSUE TITLE
[feature] Add a mechanism to filter out email addresses matching regex

### ISSUE THREAD

**Issue by fubarhouse** [blueimp/aws-smtp-relay#11]
We've a case where it would be ideal to configure the relay (running on k8s) to filter out emails if they contain problem email `from` addresses - which can be very useful for platform managers when managing client and platform reputation.

I'd love to get some thoughts to see if you're receptive to the feature?

I've submitted a PR with a draft for this feature (#10)

**Comment by blueimp** [comment]
Hey @fubarhouse, no need to create a separate issue if you already have a pull request.
I'll continue the conversation there.
