### ISSUE TITLE
[CI] Release and Docker image build

### ISSUE THREAD

**Issue by jbdelpech** [blueimp/aws-smtp-relay#14]
Hi guys,

You did a good job here with aws-smtp-relay. We would like to use it, unfortunately versioning is missing on your repository and docker as well. No versioning is a risk for us while pulling "latest" version may occur on error if you make some updates in the futur with breaking change.

Do you plan to properly tag this repository according to semantic release (as example) ? You can configure dockerhub to automatically build Docker image when you add a new tag.

As a workaround, we could fork this repository and make our own Docker image, but I think it's a shame.

Regards

**Comment by blueimp** [comment]
Thanks for the suggestion @jbdelpech.
I've tagged the latest version as `v1.0.0` and the Docker repo is set up with the same tag as well.

For any production code though I would recommend you to always build your own docker images, with the exception of official base images.

**Comment by blueimp** [comment]
Closing this as resolved.
